micronaut:
  application:
    name: grpcpix

grpc:
  server:
    port: 50051
    keep-alive-time: 1h               # <-- verificar se o canal está funcionando padrão 2h
    max-inbound-message-size: 1024


#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: 1234567
#    schema-generate: CREATE_DROP
#
#jpa.default.properties.hibernate.hbm2ddl.auto: update
#jpa.default.properties.hibernate.show_sql: true
#jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: ${ITAU_URL:`http://localhost:9091`}

bcb:
  pix:
    url: ${BCB_URL:`http://localhost:8082`}

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
